let words = ["FELIZ",
"DIFICIL","FACIL","PERSISTENCIA",
"JAVASCRIPT","GUARDAR","AZAR",
"PROGRAMACION",
"INGENIO","ASOMBRO","FUNCION","CLASES",
"OBJETO","APRENDER","ESFUERZO",
"PACIENCIA","SATISFACCION","ANALISIS",
"REEMPLAZAR"];